export const audioMap = {
  "Welcome to Angles in Geometry!": "/assets/audio/audio_welcome_to_angles_in_geometry__0.mp3",
  "Today, we are going to explore the world and learn all about angles.": "/assets/audio/audio_today__we_are_going_to_explore_the_world_and_learn_1.mp3",
  "Are you ready to begin our global geometric adventure? Let us get started!": "/assets/audio/audio_are_you_ready_to_begin_our_global_geometric_advent_2.mp3",
  "Sarah opens her book just a little bit. Then Mike opens his book all the way flat.": "/assets/audio/audio_sarah_opens_her_book_just_a_little_bit__then_mike__3.mp3",
  "Whose book makes a bigger angle? Think about it!": "/assets/audio/audio_whose_book_makes_a_bigger_angle__think_about_it__4.mp3",
  "An angle is a measure of turn!": "/assets/audio/audio_an_angle_is_a_measure_of_turn__5.mp3",
  "Let us find out what makes an angle big or small!": "/assets/audio/audio_let_us_find_out_what_makes_an_angle_big_or_small__6.mp3",
  "John lands in Paris, France.": "/assets/audio/audio_john_lands_in_paris__france__7.mp3",
  "The Eiffel Tower's legs lean out, making an angle at the ground.": "/assets/audio/audio_the_eiffel_tower_s_legs_lean_out__making_an_angle__8.mp3",
  "A small turn from a straight line is called an acute angle.": "/assets/audio/audio_a_small_turn_from_a_straight_line_is_called_an_acu_9.mp3",
  "It is smaller than a corner!": "/assets/audio/audio_it_is_smaller_than_a_corner__10.mp3",
  "Sarah visits a crossroads in New York City.": "/assets/audio/audio_sarah_visits_a_crossroads_in_new_york_city__11.mp3",
  "The streets meet in a perfect square corner — a right angle, exactly ninety degrees!": "/assets/audio/audio_the_streets_meet_in_a_perfect_square_corner___a_ri_12.mp3",
  "Mike opens the door of the Sydney Opera House all the way.": "/assets/audio/audio_mike_opens_the_door_of_the_sydney_opera_house_all__13.mp3",
  "It opens past a right angle, but is not flat. That is called an obtuse angle!": "/assets/audio/audio_it_opens_past_a_right_angle__but_is_not_flat__that_14.mp3",
  "Priya looks at the flat desert horizon near the Pyramids of Giza.": "/assets/audio/audio_priya_looks_at_the_flat_desert_horizon_near_the_py_15.mp3",
  "A perfectly flat line is a straight angle, one hundred eighty degrees.": "/assets/audio/audio_a_perfectly_flat_line_is_a_straight_angle__one_hun_16.mp3",
  "Yuki spins all the way around in a circle under the Tokyo lights.": "/assets/audio/audio_yuki_spins_all_the_way_around_in_a_circle_under_th_17.mp3",
  "A full turn is three hundred sixty degrees!": "/assets/audio/audio_a_full_turn_is_three_hundred_sixty_degrees__18.mp3",
  "Station A: Angle Maker!": "/assets/audio/audio_station_a__angle_maker__19.mp3",
  "Drag the ray to match the target angle type or degrees. See how it opens and closes!": "/assets/audio/audio_drag_the_ray_to_match_the_target_angle_type_or_deg_20.mp3",
  "Station B: Protractor Detective!": "/assets/audio/audio_station_b__protractor_detective__21.mp3",
  "Drag and rotate the protractor to align with the bottom line. Then read the angle scale and type the number!": "/assets/audio/audio_drag_and_rotate_the_protractor_to_align_with_the_b_22.mp3",
  "Station C: Angle Sums!": "/assets/audio/audio_station_c__angle_sums__23.mp3",
  "Solve the missing angle equations. Remember: straight lines make one hundred eighty degrees, and a full turn makes three hundred sixty degrees!": "/assets/audio/audio_solve_the_missing_angle_equations__remember__strai_24.mp3",
  "Let us search for the hidden angles at this landmark.": "/assets/audio/audio_let_us_search_for_the_hidden_angles_at_this_landma_25.mp3",
  "Let us search for the hidden angles at this historic landmark.": "/assets/audio/audio_let_us_search_for_the_hidden_angles_at_this_histor_26.mp3",
  "Amazing! Ten correct in a row! You are unstoppable!": "/assets/audio/audio_amazing__ten_correct_in_a_row__you_are_unstoppable_27.mp3",
  "Fantastic! Five streak! Keep going!": "/assets/audio/audio_fantastic__five_streak__keep_going__28.mp3",
  "Excellent! That is correct!": "/assets/audio/audio_excellent__that_is_correct__29.mp3",
  "Correct! Spot on!": "/assets/audio/audio_correct__spot_on__30.mp3",
  "Great job! You got it!": "/assets/audio/audio_great_job__you_got_it__31.mp3",
  "Not quite. Let us look closely at the math helper and try again!": "/assets/audio/audio_not_quite__let_us_look_closely_at_the_math_helper__32.mp3",
  "Great job exploring angles around the world! Now, let us teach our mascot what we learned.": "/assets/audio/audio_great_job_exploring_angles_around_the_world__now___33.mp3",
  "Exactly! You are a wonderful teacher!": "/assets/audio/audio_exactly__you_are_a_wonderful_teacher__34.mp3",
  "Almost! Think about how an angle measures a turn.": "/assets/audio/audio_almost__think_about_how_an_angle_measures_a_turn__35.mp3",
  "How confident do you feel about identifying and measuring angles now?": "/assets/audio/audio_how_confident_do_you_feel_about_identifying_and_me_36.mp3",
  "Congratulations! You have completed the entire journey!": "/assets/audio/audio_congratulations__you_have_completed_the_entire_jou_37.mp3",
  "Welcome to Eiffel Tower, Paris!": "/assets/audio/audio_welcome_to_eiffel_tower__paris__38.mp3",
  "Welcome to Statue of Liberty, New York!": "/assets/audio/audio_welcome_to_statue_of_liberty__new_york__39.mp3",
  "Welcome to Sydney Opera House, Sydney!": "/assets/audio/audio_welcome_to_sydney_opera_house__sydney__40.mp3",
  "Welcome to Pyramids of Giza, Cairo!": "/assets/audio/audio_welcome_to_pyramids_of_giza__cairo__41.mp3",
  "Welcome to Taj Mahal, Agra!": "/assets/audio/audio_welcome_to_taj_mahal__agra__42.mp3",
  "Welcome to Great Wall of China, Beijing!": "/assets/audio/audio_welcome_to_great_wall_of_china__beijing__43.mp3",
  "Welcome to Big Ben, London!": "/assets/audio/audio_welcome_to_big_ben__london__44.mp3",
  "Welcome to Machu Picchu, Cusco!": "/assets/audio/audio_welcome_to_machu_picchu__cusco__45.mp3",
  "Welcome to Colosseum, Rome!": "/assets/audio/audio_welcome_to_colosseum__rome__46.mp3",
  "Welcome to Burj Khalifa, Dubai!": "/assets/audio/audio_welcome_to_burj_khalifa__dubai__47.mp3"
};
